config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :users, only: [:index, :show]
  resources :portals, only: [:index, :show]
  resource :profile, only: [:show, :edit, :update]
  resource :position, only: [:update]

  resources :footprints, expect: [:destroy, :new, :edit]

end

app/models/footprint.rb
class Footprint < ActiveRecord::Base
  belongs_to :user

  def log!
    self.logs = (logs || "") + logging_text
    save!
  end

  private
  def logging_text
    <<-TEXT
#{location} at #{I18n.l updated_at}. (location: #{longitude}, #{latitude})
    TEXT
  end
end

app/models/portal.rb
class Portal < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :footprint
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/footprints_controller.rb
class FootprintsController < AuthenticateController
  before_action :set_footprint, only: [:show, :edit, :update, :destroy]

  # GET /footprints
  # GET /footprints.json
  def index
    @footprints = Footprint.all
  end

  # GET /footprints/1
  # GET /footprints/1.json
  def show
  end

  # POST /footprints.json
  def create
    if MarkFootprint.do(current_user, footprint_params)
      format.json { render :show, status: :created, location: @footprint }
    else
      format.json { render json: @footprint.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /footprints/1
  # PATCH/PUT /footprints/1.json
  def update
    respond_to do |format|
      if @footprint.update(footprint_params)
        format.html { redirect_to @footprint, notice: 'Footprint was successfully updated.' }
        format.json { render :show, status: :ok, location: @footprint }
      else
        format.html { render :edit }
        format.json { render json: @footprint.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def footprint_params
      params.require(:footprint).permit(:latitude, :longitude)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  # GET /portals
  def index
    @portals = Portal.all
  end

  # GET /portals/1
  def show
    @portal = Portal.find(params[:id])
  end
end

app/controllers/positions_controller.rb
class PositionsController < AuthenticateController
  # GET /position.json
  def show
  end

  # PATCH/PUT /position
  def update
    procedure = PositionUpdateProcedure.new(current_user, params)
    procedure.do
    redirect_to '/'
  end

  private
  def update_params
    params.permit(:latitude, :longitude, :location)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < AuthenticateController
  before_action :set_profile

  # GET /profiles/1
  def show
  end

  # GET /profiles/1/edit
  def edit
  end

  # PATCH/PUT /profiles/1
  def update
    respond_to do |format|
      if @profile.update(profile_edit_params)
        format.html { redirect_to '/profile', notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @user = @profile = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_edit_params
      params.require(:user).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/footprints_helper.rb
module FootprintsHelper
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/footprints/index.html.haml
%h1 Listing footprints

%table
  %thead
    %tr
      %th Latitude
      %th Longitude
      %th User
      %th
      %th
      %th

  %tbody
    - @footprints.each do |footprint|
      %tr
        %td= footprint.latitude
        %td= footprint.longitude
        %td= footprint.user
        %td= link_to 'Show', footprint
        %td= link_to 'Edit', edit_footprint_path(footprint)
        %td= link_to 'Destroy', footprint, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Footprint', new_footprint_path

app/views/footprints/show.html.haml
%p#notice= notice

%p
  %b Latitude:
  = @footprint.latitude
%p
  %b Longitude:
  = @footprint.longitude
%p
  %b User:
  = @footprint.user

= link_to 'Edit', edit_footprint_path(@footprint)
\|
= link_to 'Back', footprints_path

app/views/home/index.html.haml
%h1 Ningress

- unless signed_in?
  = link_to 'login / sign up', '/users/sign_in'
- else
  = link_to 'logout', destroy_user_session_path, method: :delete, "data-confirm" => "Are you sure?"

  - @user = current_user
  = render 'profiles/show'

  %br
  = render 'position/acquire'

  - if current_user.footprint.present?
    #footprint
      %div
        longitude:
        = current_user.footprint.longitude
      %div
        latitude:
        = current_user.footprint.latitude
      %div
        localtion:
        = current_user.footprint.location
      %div
        %strong
          Updated:
          =l current_user.footprint.updated_at.in_time_zone('Asia/Tokyo')

  %h2 Logs
  %p
    = simple_format current_user.footprint.logs

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nungress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=false' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/portals/index.html.haml
%p#notice= notice

%h1 Listing Portals

%table
  %thead
    %tr
      %th Name
      %th Latitude
      %th Longitude
      %th{:colspan => "3"}
  %tbody
    - @portals.each do |portal|
      %tr
        %td=link_to portal.name, |
          "https://maps.google.co.jp/maps?" + |
          "q=#{portal.latitude},#{portal.longitude}&iwloc=A", target: "_blank" |
        %td= portal.latitude
        %td= portal.longitude
        %td= link_to 'Show', portal

app/views/portals/show.html.haml
%p#notice= notice

%p
  %strong Name:
  = @portal.name
%p
  %strong Longitude:
  = @portal.longitude
%p
  %strong Latitude:
  = @portal.latitude

= link_to 'Back', portals_path

app/views/position/_acquire.html.haml
%button#acquireButton{ onclick: 'acquire_current_position()' }
  Acquire Current Position
%p#acquiringMessage

= form_tag '/position', method: :put, id: "positionUpdateForm" do
  %input#positionLatitude{ type: :hidden, name: :latitude }
  %input#positionLongitude{ type: :hidden, name: :longitude }
  %input#positionAddress{ type: :hidden, name: :location }

app/views/profiles/_show.html.haml
%h1
  = @user.name
  = "(Level: " + @user.level.to_s + ")"

%table
  %tr
    %th Name
    %td= @user.name
  %tr
    %th Level
    %td= @user.level
  %tr
    %th Life
    %td= @user.life
  %tr
    %th ATK
    %td= @user.atk
  %tr
    %th DEF
    %td= @user.def

= link_to 'Edit Profile', '/profile/edit'

app/views/profiles/edit.html.haml
%h1
  = @user.name
  = "(Level: " + @user.level.to_s + ")"

= form_for @user, url: '/profile' do |f|
  %table
    %tr
      %th Name
      %td=f.text_field :name
  = f.submit

app/views/profiles/show.html.haml
= render 'show'

app/views/users/edit.html.haml
%h1
  = @user.name
  = "(Level: " + @user.level.to_s + ")"

= form_for @edit do
  %table
    %tr
      %th Name
      %td= @user.name
    %tr
      %th Level
      %td= @user.level
    %tr
      %th Life
      %td= @user.life

app/views/users/index.html.haml
%h1 Nugress

%table
  %thead
    %tr
      %td id
      %td Name
      %td Level
  - User.all.each do |user|
    %tbody
      %tr
        %td= user.id
        %td= user.name
        %td= user.level

app/views/users/show.html.haml
%h1
  = @user.name
  = "(Level: " + @user.level.to_s + ")"

%table
  %tr
    %th Name
    %td= @user.name
  %tr
    %th Level
    %td= @user.level
  %tr
    %th Life
    %td= @user.life